=== whwlsfb/BurpCrypto/lib/org/fife/ui/rsyntaxtextarea/themes/theme.dtd
<!-- DTD for RSyntaxTextArea Theme XML. See /themes folder for examples. -->
<!ELEMENT RSyntaxTheme (baseFont?, background, caret, selection,
      currentLineHighlight, marginLine, markAllHighlight, markOccurrencesHighlight,
      matchedBracket, hyperlinks, secondaryLanguages, gutterBackground?, gutterBorder, lineNumbers,
      foldIndicator, iconRowHeader?, tokenStyles)>
<!ELEMENT background EMPTY>
<!ELEMENT baseFont EMPTY>
<!ELEMENT caret EMPTY>
<!ELEMENT selection EMPTY>
<!ELEMENT currentLineHighlight EMPTY>
<!ELEMENT marginLine EMPTY>
<!ELEMENT markAllHighlight EMPTY>
<!ELEMENT markOccurrencesHighlight EMPTY>
<!ELEMENT matchedBracket EMPTY>
<!ELEMENT hyperlinks EMPTY>
<!ELEMENT secondaryLanguages (language+)>
<!ELEMENT language EMPTY>
<!ELEMENT gutterBackground EMPTY>
<!ELEMENT gutterBorder EMPTY>
<!ELEMENT lineNumbers EMPTY>
<!ELEMENT foldIndicator EMPTY>
<!ELEMENT iconRowHeader EMPTY>
<!ELEMENT tokenStyles (style+)>
<!ELEMENT style EMPTY>

<!ATTLIST RSyntaxTheme
      version  CDATA #REQUIRED>
<!ATTLIST background
      color    CDATA #REQUIRED>
<!ATTLIST baseFont
      family    CDATA #IMPLIED
      size      CDATA #IMPLIED>
<!ATTLIST caret
      color     CDATA #REQUIRED>
<!ATTLIST selection
      fg        CDATA #IMPLIED
      useFG     (true|false) "true"
      bg        CDATA #REQUIRED
      roundedEdges (true|false) "false">
<!ATTLIST currentLineHighlight
      color     CDATA #REQUIRED
      fade      (true|false) "false">
<!ATTLIST marginLine
      fg         CDATA #REQUIRED>
<!ATTLIST markAllHighlight
      color      CDATA #REQUIRED>
<!ATTLIST markOccurrencesHighlight
      color      CDATA #REQUIRED
      border     (true|false) "false">
<!ATTLIST matchedBracket
      fg            CDATA #REQUIRED
      bg            CDATA #IMPLIED
      highlightBoth (true|false) "false"
      animate       (true|false) "false">
<!ATTLIST hyperlinks
      fg         CDATA #REQUIRED>
<!ATTLIST language
      index      (1|2|3) #REQUIRED
      bg         CDATA   #REQUIRED>
<!ATTLIST gutterBackground
      color      CDATA #REQUIRED>
<!ATTLIST gutterBorder
      color      CDATA #REQUIRED>
<!ATTLIST lineNumbers
      fg         CDATA #REQUIRED
      fontFamily CDATA #IMPLIED
      fontSize   CDATA #IMPLIED>
<!ATTLIST foldIndicator
      fg          CDATA #REQUIRED
      iconBg      CDATA #REQUIRED
      iconArmedBg CDATA #IMPLIED>
<!ATTLIST iconRowHeader
      activeLineRange CDATA #REQUIRED
      inheritsGutterBG (true|false) "false">
<!ATTLIST style
      token      CDATA #REQUIRED
      fg         CDATA #IMPLIED
      bg         CDATA #IMPLIED
      fontFamily CDATA #IMPLIED
      fontSize   CDATA #IMPLIED
      bold       (true|false) "false"
      italic     (true|false) "false"
      underline  (true|false) "false">

=== whwlsfb/BurpCrypto/lib/org/fife/ui/rsyntaxtextarea/themes/monokai.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE RSyntaxTheme SYSTEM "theme.dtd">

<!-- "Monokai" inspired theme for use with RSyntaxTextArea. -->

<RSyntaxTheme version="1.0">

    <!--  General editor colors. -->
    <background color="2E2E2E"/>
    <caret color="D2D2D2"/>
    <selection useFG="false" bg="4C4C4C" roundedEdges="false"/>
    <currentLineHighlight color="383A38" fade="false"/>
    <marginLine fg="394448"/>
    <markAllHighlight color="383A38"/>
    <markOccurrencesHighlight color="383A38" border="false"/>
    <matchedBracket fg="F0F0F0" bg="2E2E2E" highlightBoth="true" animate="true"/>
    <hyperlinks fg="A082BD"/>
    <secondaryLanguages>
        <language index="1" bg="333344"/>
        <language index="2" bg="223322"/>
        <language index="3" bg="332222"/>
    </secondaryLanguages>

    <!-- Gutter styling. -->
    <gutterBorder color="81969A"/>
    <lineNumbers fg="81969A"/>
    <foldIndicator fg="6A8088" iconBg="2f383c" iconArmedBg="3f484c"/>
    <iconRowHeader activeLineRange="878787"/>

    <!-- Syntax tokens. -->
    <tokenStyles>
        <style token="IDENTIFIER" fg="F9F9F9"/>
        <style token="RESERVED_WORD" fg="F92672" bold="false"/>
        <style token="RESERVED_WORD_2" fg="A6E22E" bold="true"/>
        <style token="ANNOTATION" fg="FD971F"/>
        <style token="COMMENT_DOCUMENTATION" fg="878787"/>
        <style token="COMMENT_EOL" fg="6C6C6C"/>
        <style token="COMMENT_MULTILINE" fg="93a1a1"/>
        <style token="COMMENT_KEYWORD" fg="FD971F"/>
        <style token="COMMENT_MARKUP" fg="FD971F"/>
        <style token="FUNCTION" fg="52E3F6"/>
        <style token="DATA_TYPE" fg="52E3F6" bold="true"/>
        <style token="LITERAL_BOOLEAN" fg="FD971F" bold="true"/>
        <style token="LITERAL_NUMBER_DECIMAL_INT" fg="AE81FF"/>
        <style token="LITERAL_NUMBER_FLOAT" fg="AE81FF"/>
        <style token="LITERAL_NUMBER_HEXADECIMAL" fg="AE81FF"/>
        <style token="LITERAL_STRING_DOUBLE_QUOTE" fg="E3ED77"/>
        <style token="LITERAL_CHAR" fg="A6E22E"/>
        <style token="LITERAL_BACKQUOTE" fg="EC7600"/>
        <style token="MARKUP_TAG_DELIMITER" fg="F92672"/>
        <style token="MARKUP_TAG_NAME" fg="ABBFD3" bold="true"/>
        <style token="MARKUP_TAG_ATTRIBUTE" fg="B3B689"/>
        <style token="MARKUP_TAG_ATTRIBUTE_VALUE" fg="e1e2cf"/>
        <style token="MARKUP_COMMENT" fg="878787"/>
        <style token="MARKUP_DTD" fg="A082BD"/>
        <style token="MARKUP_PROCESSING_INSTRUCTION" fg="A082BD"/>
        <style token="MARKUP_CDATA" fg="d5e6f0"/>
        <style token="MARKUP_CDATA_DELIMITER" fg="FD971F"/>
        <style token="MARKUP_ENTITY_REFERENCE" fg="F92672"/>
        <style token="OPERATOR" fg="F92672"/>
        <style token="PREPROCESSOR" fg="A082BD"/>
        <style token="REGEX" fg="AE81FF"/>
        <style token="SEPARATOR" fg="F0F0F0"/>
        <style token="VARIABLE" fg="FD971F" bold="false"/>
        <style token="WHITESPACE" fg="F9F9F9"/>

        <style token="ERROR_IDENTIFIER" fg="F9F9F9" bg="d82323"/>
        <style token="ERROR_NUMBER_FORMAT" fg="F9F9F9" bg="d82323"/>
        <style token="ERROR_STRING_DOUBLE" fg="F9F9F9" bg="d82323"/>
        <style token="ERROR_CHAR" fg="F9F9F9" bg="d82323"/>
    </tokenStyles>

</RSyntaxTheme>
